before_script:
  - ./bin/install_deps
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS galette_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database galette_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -d galette_tests -a -f galette/install/sql/pgsql.sql -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS galette_tests;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'use galette_tests; source galette/install/sql/mysql.sql;'; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then rm tests/galette.test.sqlite & touch tests/galette.test.sqlite; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then sqlite3 tests/galette.test.sqlite < galette/install/sql/sqlite.sql; fi"
  - sh -c "cp tests/config/$DB-config.inc.php galette/config/config.inc.php"
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
script: php mageekguy.atoum.phar -mcn 1 -bf tests/TestsBootstrap.php -d tests/Galette/
language: php
php:
  - 5.3
  - 5.4
  - 5.5
env:
  - DB=pgsql
  - DB=mysql
  - DB=sqlite
notifications:
  irc:
    channels:
      - "irc.oftc.net#galette"
    template:
      - "%{build_number} by %{author} on %{branch}: %{message} "
      - "Build details: %{build_url}"
branches:
  only:
    - develop
